config/routes.rb
Rails.application.routes.draw do
  root 'blogs#top'
  resources :users
  resources :sessions, only: [:new, :create, :edit, :destroy]
  resources :favorites, only: [:create, :destroy]
  
  resources :blogs do
    collection do
      post :confirm
      get :favorite
      get :top
    end
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :content, length: { in: 1..140 }
  
  #アソシエーション
  belongs_to :user, foreign_key: "user_id"
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  #アソシエーション
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
                    
  before_save { email.downcase! }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password, length: {minimum: 6}, on: :update, allow_blank: true
  
  #アソシエーション
  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :edit, :show, :destroy, :favorite]
  
  def top
    
  end
  
  def index
    @blogs = Blog.all
    @user = current_user
  end
  
  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end
  
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    @blog.image.retrieve_from_cache!(params[:cache][:image]) if params[:cache][:image].present?
    
    respond_to do |format|
      if @blog.save
        BlogMailer.blog_mail(@blog).deliver
        format.html { redirect_to @blog, notice: "投稿しました" }
        format.json { render :index, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
    
  end
  
  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end
  
  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: "記事を編集しました"
    else
      render 'edit'
    end
  end
  
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "記事を削除しました"
  end
  
  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    render :new if @blog.invalid?
  end
  
  def favorite
    @blogs = current_user.favorite_blogs
  end
  
  private
    def blog_params
      params.require(:blog).permit(:title, :content, :image, :image_cache)
    end
    
    def set_blog
      @blog = Blog.find(params[:id])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    @favorites = favorite
    redirect_to blogs_url, notice: "#お気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    redirect_to blogs_url, notice: "#お気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to blogs_path
    else
      flash[:danger] = 'ログインに失敗しました'
      redirect_to new_session_path
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :logged_in_user, only: [:edit, :show]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    else
      render 'new'
    end
  end
  
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "登録情報を更新しました"
    else
      redirect_to user_path
    end
  end
  
  def edit
    
  end
  
  def show
    
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def logged_in_user
    redirect_to new_session_url unless logged_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    
    <%= form_with(model: @blog, local: true ,url: choose_new_or_edit) do |form| %>
      <% if @blog.errors.any? %>
        <div id="error_explanation">
          <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
            <% @blog.errors.full_messages.each do |msg| %>
              <p><%= msg %></p>
            <% end %>
        </div>
      <% end %>
    
      <%= form.label :title %>
      <%= form.text_field :title, size:40 %>
     
      <%= form.label :content %>
      <%= form.text_area :content, :size => "42x3" %>
      
      <p><%= form.file_field :image %></p>
      <%= form.hidden_field :image_cache %>
     
      <%= form.submit "投稿", :class => 'btn btn-success' %>
    <% end %>
    <br>
    <%= link_to "戻る", blogs_path, :class => 'btn btn-default btn-block' %>
  </div>
</div>

app/views/blogs/confirm.html.erb
<div class="container">
  <h3>投稿しますか？</h3>
    <%= form_with(model: @blog, local: true) do |form| %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :image %>

      <div class="row">
        <article class="col-xs-12 col-md-4">タイトル</article>
        <article class="col-xs-12 col-md-8"><%= @blog.title %></article>
      
        <article class="col-xs-12 col-md-4">内容</article>
        <article class="col-xs-12 col-md-8"><%= @blog.content %></article>
        
        <article class="col-xs-12 col-md-4">画像</article>
        <article class="col-xs-12 col-md-8"><%= image_tag @blog.image.url if @blog.image.present? %></article>
          <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
        
      </div>
      
      <p><%= form.submit "投稿", :class => 'btn btn-success' %></p>
    <% end %>
    
      <br>
      <%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
        <%= form.hidden_field :title %>
        <%= form.hidden_field :content %>
        <%= form.hidden_field :image %>
        
        <p><%= form.submit "戻る", name: 'back', :class => 'btn btn-default btn-block' %></p>
      <% end %>
    </article>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
  <h2>記事を編集する</h2>
  <%= render 'form' %>
</div>

app/views/blogs/favorite.html.erb
<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <h1>お気に入りリスト</h1>
  
    <% @blogs.each do |blog| %>
      <div class="row">
        <article class="col-xs-12 col-md-4"><b><%= blog.title %></b></article>
        <article class="col-xs-12 col-md-4"><%= blog.content %></article>
        
        <article class="col-xs-12 col-md-4">
          <%= link_to '詳細', blog_path(blog.id), :class => 'btn btn-info' %>
        </article>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
  <h1>記事一覧</h1>
  
  <p><%= notice %></p>

  <% @blogs.each do |blog| %>
    <div class="row">
      <article class="col-xs-12 col-md-4"><b><%= blog.title %></b></article>
      <article class="col-xs-12 col-md-4"><%= blog.content %></article>
      
      <article class="col-xs-12 col-md-4">
        <%= link_to '詳細', blog_path(blog.id), :class => 'btn btn-info' %>
      
        <% if blog.user == current_user %>
          <%= link_to "編集", edit_blog_path(blog.id), :class => 'btn btn-default' %>
          <%= link_to '削除', blog_path(blog.id), method: :delete, data: { confirm: '消していいですか？' }, :class => 'btn btn-danger' %>
        <% end %>
      </article>
    </div>
  <% end %>
  
  <br>
  <p><%= link_to '新規投稿', new_blog_path, :class => 'btn btn-success' %></p>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <h2>新規投稿</h2>
  <%= render 'form' %>
</div>

app/views/blogs/show.html.erb
<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
  <h1>詳細画面</h1>
    <p><%= notice %></p>
  
    <table>
      <tr><td><b>タイトル</b></td></tr>
      <tr><td><%= @blog.title %></td></tr>
      
      <tr><td><b>内容</b></td></tr>
      <tr><td><%= @blog.content %></td></tr>
      
      <tr><td><%= image_tag @blog.image.url %></td></tr>
    </table>
    
    <% unless @blog.user_id == current_user.id %>
      <% if @favorite.present? %>
        <%= link_to 'お気に入り解除', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
    <% end %>
    
    <p><%= link_to "戻る", blogs_path, :class => 'btn btn-default' %></p>
  </div>
</div>

app/views/blogs/top.html.erb
  <div class="row">
    <article class="col-xs-12 col-md-6">
      <%= image_tag 'my_icon.jpg', :class => "img-responsive center-block" %>
    </article>
    
    <article class="col-xs-12 col-md-6">
      <h2>Plogs</h2><br>
        <p>これは「ブログっぽい」何かです。</p>
        <p>タイトルをつけることができます。</p>
        <p>本文も書くことができます。</p>
        
        <br>
        
        <% if logged_in? %>
          <%= link_to "List", blogs_path, :class => 'btn btn-info' %>
          <%= link_to "Logout", session_path(current_user.id), method: :delete, :class => 'btn btn-danger' %>
        <% else %>
          <%= link_to "Sign up", new_user_path, :class => 'btn btn-success' %>
          <%= link_to "Login", new_session_path, :class => 'btn btn-primary' %>
        <% end %>
    </article>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plog</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">Plog</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <a class="navbar-brand" href="/blogs/top">HOME</a>
          </div>
            <div id="gnavi" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                
                <li><%= link_to "リスト", blogs_path %></li>
                <% if logged_in? %>
                  <li><%= link_to 'つぶやく', new_blog_path %></li>
                  <li><%= link_to "お気に入り", favorite_blogs_path %></li>
                  <li><%= link_to "設定", user_path(current_user.id) %></li>
                  <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
                <% else %>
                  <li><%= link_to "会員登録", new_user_path %></li>
                  <li><%= link_to "ログイン", new_session_path %></li>
                <% end %>
                
              </ul>
            </div>
        </div>
      </nav>
    </header>
    
    <%= yield %>
    
    <footer>
      <div class="footer_content row">
        <div class="col-xs-12 col-md-12">
          <p>Testページ</p>
          <p>© 2017_09class HASHIMOTO Jun.</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">

    <%= form_with(model: @user, local: true) do |f| %>
    
      <p><%= f.label :image %></p>
      <p><%= f.file_field :image, id: :user_image %></p>
      <%= f.hidden_field :image_cache %>
    
      <p><%= f.label :name %></p>
      <p><%= f.text_field :name %></p>
      
      <p><%= f.label :email %></p>
      <p><%= f.email_field :email %></p>

      <p><%= f.submit "編集", class: "btn btn-success" %></p>
    <% end %>
  </div>
 </div>

app/views/users/new.html.erb
<!-- userアクション -->
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <center><h1>Sign up</h1></center>
      <br>
    
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
             </ul>
         </div>
      <% end %>
      <br>
      <%= form_with(model: @user, local: true) do |f| %>  
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.email_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "登録する", :class => 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">

    <h1>登録情報</h1>
    
    <p><%= notice %></p>
    
      <p><%= image_tag @user.image.url, class: "user-img" %></p>
      <p>Name: <%= @user.name %></p>
      <p>Mail: <%= @user.email %></p>
    
    <% if logged_in? %>
      <p><%= link_to "編集", edit_user_path(current_user.id) %></p>
    <% end %>
  </div>
</div>